### ISSUE TITLE
How to use with the drawer

### ISSUE THREAD

**Issue by larserikfinholt** [arabsight/aurelia-mdc-plugin#1]
First, thanks for the work on this plugin. 

How could I get a reference to the initialized mdc class?
From what I understand I need to set the open property on the MDCTemporaryDrawer to open it. 

Or maybe there's another way?

**Comment by arabsight** [comment]
Hi @larserikfinholt, every time an mdc component gets initialized an MDCClass gets attached to the root div (element with the mdc selector), in the case of the drawer its MDCTemporaryDrawer, so you can either put a ref on the element or query the DOM. 

here's how to open the drawer:

```html
<div class="mdc-temporary-drawer mdc-typography" ref="drawer">
...
</div>
```
```js
this.drawer.MDCTemporaryDrawer.open = true;
```

**Comment by larserikfinholt** [comment]
Ahhh.... of course.  Nice to know about the ref attribute, never used that. Thanks
