### ISSUE TITLE
Manually adding MDCRipple doesn't seem to work

### ISSUE THREAD

**Issue by djensen47** [arabsight/aurelia-mdc-plugin#2]
I was trying to get ripple working on a list and I followed these directions:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#using-ink-ripples-for-interactive-lists

But the ripple doesn't work unless I add `mdc-ripple-surface` to the class of the list item.

**Comment by arabsight** [comment]
Hi, @djensen47 adding the mdc-ripple-surface will add *data-mdc-auto-init="MDCRipple"* and call *autoInit()*, that's how the plugin works so you don't have to do it for each component. if you don't like the way this works or you have a better suggestion, let me know.

**Comment by djensen47** [comment]
Maybe the issue is the inconsistency of the MDC docs on how to do a ripple?
