### ISSUE TITLE
mdc-tab will be autoinited twice

### ISSUE THREAD

**Issue by larserikfinholt** [arabsight/aurelia-mdc-plugin#3]
It seems like autoinit on the mc-tab-bar will do call a autoinit on each mdc-tab's also. This will cause some mdc errors. Removing `'mdc-tab': 'MDCTab',` from congig.ts seems to fix the issue. I'm not sure if this is a bug in MDC library, but or it should be removed from this plugin. Leaving it here as a comment in case others have the same problem.

**Comment by arabsight** [comment]
@larserikfinholt, thanks. It was a plugin issue, the MDCTabBar looks for children (TABs) and initialize them. 
fixed in 0.4.2
