### ISSUE TITLE
Question: `mdl-target`

### ISSUE THREAD

**Issue by reeddunkle** [arabsight/aurelia-mdc-plugin#5]
I get the error: `Unable to resolve aurelia-mdc-plugin/mdl-target`, and I think it stems from this plugin's [`package.json` L77](https://github.com/arabsight/aurelia-mdc-plugin/blob/master/package.json#L77).

Can you help shed light on this, why it's needed, and how to resolve the error?

**Comment by arabsight** [comment]
Hi, sorry for the late response, mdc-target is a custom attribute responsible for auto initialization of the MDC Component. what build system are you using?

**Comment by reeddunkle** [comment]
Thanks for getting back to me.
In the `package.json`, it says `mdl-target` (note, mdL instead of mdC)

```
    "aurelia": {
        "build": {
            "resources": [
                "mdl-target"
            ]
        }
    },
```

I'm using webpack

**Comment by arabsight** [comment]
oh, alright fixed the typo and pushed an update.

**Comment by reeddunkle** [comment]
Thank you
